### ISSUE TITLE
NOT_FOUND incorrectly showing for several different schools

### ISSUE THREAD

**Issue by ThatTallGuy21** [daviswieck/ha-college-football#4]
I've made 5 attempts at getting a school to display and have only gotten it to work once with TEX. For TEX, the sensor state shows correctly as POST. However, I'm getting a sensor state of NOT_FOUND for ALA, ND, MICH, and PSU despite all of them playing recently and in the top 25.

**Comment by daviswieck** [comment]
Change the api endpoint in the Const file to https://site.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard

This is for top 25 teams.

**Comment by ThatTallGuy21** [comment]
Ah, that did the trick! I missed that. Thank you

**Comment by Exit2Studios** [comment]
I realize this is closed, but I'm unable to get anything to show.  Is there a better way to add multiple teams than using the Integrations UI in HA?

**Comment by daviswieck** [comment]
In your config file add:
Change teams to whatever you want them to. 

```
sensor:
  - platform: college_football
    team_id: 'TTU'
    
  - platform: college_football
    team_id: 'OKST'
```
